<?php

namespace App\Filament\Resources\Marksheets\Schemas;

use App\Models\Marksheet;
use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Schema;

class MarksheetInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->columns(2)
            ->components([
                Section::make('Student')
                    ->columns(3)
                    ->schema([
                        TextEntry::make('student.user.name')
                            ->label('Name'),
                        TextEntry::make('student.class.name')
                            ->label('Class'),
                        TextEntry::make('student.section.name')
                            ->label('Section'),
                        TextEntry::make('student.roll_no')
                            ->label('Roll No'),
                    ]),

                Section::make('Exam')
                    ->columns(2)
                    ->schema([
                        TextEntry::make('exam.examType.name')
                            ->label('Exam Type'),
                        TextEntry::make('exam.session_year')
                            ->label('Session Year'),
                    ]),

                Section::make('Generation Status')
                    ->columns(3)
                    ->schema([
                        IconEntry::make('is_generated')
                            ->label('Generated')
                            ->boolean(),
                        TextEntry::make('file_generated_at')
                            ->label('Generated At')
                            ->dateTime('d M Y, h:i A'),
                        TextEntry::make('generatedBy.name')
                            ->label('Generated By')
                            ->placeholder('System (queue job)'),
                    ]),
            ]);
    }
}
